# Spring config
spring:
  application:
    name: Common Service  # Project's Config
  datasource:
    url: jdbc:postgresql://192.168.210.201:5433/loc_db  # Project's Config
    username: fanatic  # Project's Config
    password: Fanatic@123  # Project's Config
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.order_by.default_null_ordering: last
    hibernate.use-new-id-generator-mappings: true
